Fix support for the BXDECAY0_RESOURCE_DIR env in bxdecay0-config script

diff --git a/bxdecay0-config.in b/bxdecay0-config.in
--- a/bxdecay0-config.in
+++ b/bxdecay0-config.in
@@ -28,6 +28,14 @@
 
 APPNAME="bxdecay0-config"
 prefix_dir="@CMAKE_INSTALL_PREFIX@"
+if [ -n "${BXDECAY0_PREFIX_DIR}" ]; then
+    echo >&2 "[log] Overriding BxDecay0 prefix dir from env 'BXDECAY0_PREFIX_DIR'..."
+    if [ ! -d "${BXDECAY0_PREFIX_DIR}" ]; then
+	echo >&2 "[error] Overridden BxDecay0 prefix dir '${BXDECAY0_PREFIX_DIR}' does not exist!"
+	exit 0
+    fi
+    prefix_dir="${BXDECAY0_PREFIX_DIR}"
+fi
 version_str="@BxDecay0_VERSION@"
 orig_version_str="@BxDecay0_DECAY0_VERSION@"
 lib_dir="${prefix_dir}/@CMAKE_INSTALL_LIBDIR@"
@@ -36,6 +44,14 @@ inc_dir="${prefix_dir}/@CMAKE_INSTALL_INCLUDEDIR@"
 data_dir="${prefix_dir}/@CMAKE_INSTALL_DATADIR@/@BxDecay0_TAG@"
 example_dir="${data_dir}/examples"
 resource_dir="${data_dir}/resources"
+if [ -n "${BXDECAY0_RESOURCE_DIR}" ]; then
+    echo >&2 "[log] Overriding BxDecay0 resource dir from env 'BXDECAY0_RESOURCE_DIR'..."
+    if [ ! -d "${BXDECAY0_RESOURCE_DIR}" ]; then
+	echo >&2 "[error] Overriden BxDecay0 resource dir '${BXDECAY0_RESOURCE_DIR}' does not exist!"
+	exit 0
+    fi
+    resource_dir="${BXDECAY0_RESOURCE_DIR}"
+fi
 # cmake_dir="${prefix_dir}/@CMAKE_INSTALL_CMAKEDIR@/@BxDecay0_TAG@"
 cmake_dir="${prefix_dir}/@CMAKE_INSTALL_CMAKEDIR@/BxDecay0"
 
